### ISSUE TITLE
Identify measurements belonging to same GCP which are out of sequence - possible enhancement (not urgent)

### ISSUE THREAD

**Issue by retoweiss** [ubx/RW5toCSV#12]
Until now we claimed that all measurements belonging to the same GCP are continuous, that's not always true, as it turns out.

Example: GCP5 can only be measured once and maybe with a a signifficant HSDV/VSDV, hence we continue with other GCPs and come back later.
- GCP4: PM03,PM04,PM05  // continuous
- GCP5: PM06, PM22, PM23, PM33  // not continuous
- GCP6: PM07, PM10, PM11  // not continuous

In order to recognize these cases, we can no longer process the measurement one by one. Instead, we have to temporary store them in an array (or so) . Upon identifying all the measurements for a given GCP, we then can consider every sinle measurement, not only the next one.

**Comment by ubx** [comment]
Ich schliesse dieses iIssue mal. Falls nötig machen wir ein neues.
